name: Tests
on:
  push:
    branches:
      - main
      - "*.x"
    paths-ignore:
      - "docs/**"
      - "*.md"
      - "*.rst"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "*.md"
      - "*.rst"
jobs:
  tests:
    name: ${{ matrix.name || matrix.python }}
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { python: "3.14" }
          - { python: "3.13" }
          - { python: "3.12" }
          - { python: "3.11" }
    services:
      memcached:
        image: memcached:1.6.41
        ports:
          - 11212:11211
        # health checks
        options: >-
          --health-cmd "timeout 5 bash -c 'echo > /dev/tcp/127.0.0.1/11211'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:8.6.3
        ports:
          - 6360:6379
        # health checks
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          enable-cache: true
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python }}
          allow-prereleases: true
      - name: install external dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libmemcached-dev
      - run: uv sync --group dev --group tests
      - run: uv run tox run -e ${{ matrix.tox || format('py{0}', matrix.python) }}
